<?php

declare(strict_types=1);

namespace App\Catalogue;

/**
 * The merch shop of the talk: prepared, not typed live. The importer reads it, nothing else does.
 */
final class CatalogueData
{
    /**
     * @return array<string, array{type: string, name: string, group: string, options?: array<string, string>, config?: array<string, string>, localized?: bool, filterable?: bool}>
     */
    public function attributes(): array
    {
        return [
            'colour' => [
                'type' => 'options',
                'name' => 'Colour',
                'group' => 'Look',
                'options' => [
                    'black' => 'Black',
                    'white' => 'White',
                    'teal' => 'Teal',
                    'mustard' => 'Mustard',
                    'navy' => 'Navy',
                    'red' => 'Red',
                    'yellow' => 'Yellow',
                ],
                'filterable' => true,
            ],
            'size' => [
                'type' => 'options',
                'name' => 'Size',
                'group' => 'Look',
                'options' => ['s' => 'S', 'm' => 'M', 'l' => 'L', 'one-size' => 'One size'],
                'filterable' => true,
            ],
            'fit' => [
                'type' => 'options',
                'name' => 'Fit',
                'group' => 'Look',
                'options' => ['slim' => 'Slim', 'regular' => 'Regular', 'relaxed' => 'Relaxed'],
                'filterable' => true,
            ],
            'print_motif' => [
                'type' => 'text',
                'name' => 'Print',
                'group' => 'Look',
            ],
            'material' => [
                'type' => 'options',
                'name' => 'Material',
                'group' => 'Material & care',
                'options' => [
                    'cotton' => 'Cotton',
                    'organic-cotton' => 'Organic cotton',
                    'fleece' => 'Cotton fleece',
                    'polyester' => 'Polyester',
                    'canvas' => 'Canvas',
                    'ceramic' => 'Ceramic',
                    'steel' => 'Stainless steel',
                    'vinyl' => 'Vinyl',
                    'paper' => 'Paper',
                    'rubber' => 'Rubber',
                ],
                'filterable' => true,
            ],
            'wash_temperature' => [
                'type' => 'number',
                'name' => 'Wash at',
                'group' => 'Material & care',
                'config' => ['unit' => 'CELSIUS', 'displayFormat' => '%value% %unit%'],
                'filterable' => true,
            ],
            'dishwasher_safe' => [
                'type' => 'boolean',
                'name' => 'Dishwasher safe',
                'group' => 'Material & care',
            ],
            'origin' => [
                'type' => 'options',
                'name' => 'Made in',
                'group' => 'Material & care',
                'options' => [
                    'portugal' => 'Portugal',
                    'germany' => 'Germany',
                    'poland' => 'Poland',
                    'austria' => 'Austria',
                ],
                'filterable' => true,
            ],
            'weight' => [
                'type' => 'number',
                'name' => 'Weight',
                'group' => 'Specs',
                'config' => ['unit' => 'GRAM', 'displayFormat' => '%value% %unit%'],
                'filterable' => true,
            ],
            'volume' => [
                'type' => 'number',
                'name' => 'Volume',
                'group' => 'Specs',
                'config' => ['unit' => 'MILLILITER', 'displayFormat' => '%value% %unit%'],
                'filterable' => true,
            ],
            'release_date' => [
                'type' => 'date',
                'name' => 'Release date',
                'group' => 'Good to know',
                'config' => ['displayFormat' => 'd MMMM y'],
                'filterable' => true,
            ],
            'limited_edition' => [
                'type' => 'boolean',
                'name' => 'Limited edition',
                'group' => 'Good to know',
                'filterable' => true,
            ],
            'fun_fact' => [
                'type' => 'text',
                'name' => 'Fun fact',
                'group' => 'Good to know',
                'localized' => true,
            ],
        ];
    }

    /**
     * A family is the set of attributes of one kind of product: `required` blocks saving without a value,
     * `variant` moves the attribute to the variants.
     *
     * @return array<string, array{name: string, attributes: array<string, array{required?: bool, variant?: bool}>}>
     */
    public function families(): array
    {
        return [
            'clothing' => [
                'name' => 'Clothing',
                'attributes' => [
                    'material' => ['required' => true],
                    'fit' => [],
                    'origin' => [],
                    'weight' => ['required' => true],
                    'wash_temperature' => [],
                    'release_date' => [],
                    'print_motif' => [],
                    'fun_fact' => [],
                    'limited_edition' => [],
                    'colour' => ['variant' => true],
                    'size' => ['variant' => true],
                ],
            ],
            'accessories' => [
                'name' => 'Accessories',
                'attributes' => [
                    'material' => ['required' => true],
                    'origin' => [],
                    'weight' => [],
                    'volume' => [],
                    'dishwasher_safe' => [],
                    'release_date' => [],
                    'print_motif' => [],
                    'fun_fact' => [],
                    'limited_edition' => [],
                    'colour' => ['variant' => true],
                ],
            ],
        ];
    }

    /**
     * @return list<array{code: string, family: string, title: string, claim: string, description: string, image: string, attributes: array<string, bool|float|int|string>, associations?: array<string, list<string>>}>
     */
    public function products(): array
    {
        return [
            [
                'code' => 'TS-1001',
                'family' => 'clothing',
                'title' => 'Hello World T-Shirt',
                'claim' => 'Your first T-shirt. It says hello.',
                'description' => '<p>A soft cotton T-shirt with a small print on the chest. Every developer starts with this sentence.</p>',
                'image' => 'hello-world-t-shirt-teal.jpg',
                'attributes' => [
                    'material' => 'organic-cotton',
                    'fit' => 'regular',
                    'origin' => 'portugal',
                    'weight' => 180,
                    'wash_temperature' => 40,
                    'release_date' => '2026-03-02',
                    'print_motif' => 'Hello, World!',
                    'fun_fact' => 'The first Hello, World program is from the 1970s.',
                ],
                'associations' => ['accessory' => ['MG-4001', 'ST-5001'], 'alternative' => ['TS-1002']],
            ],
            [
                'code' => 'TS-1002',
                'family' => 'clothing',
                'title' => 'It Works On My Machine T-Shirt',
                'claim' => 'The most honest sentence in IT.',
                'description' => '<p>A classic cotton T-shirt with a big sentence on the front. Wear it on your next deploy.</p>',
                'image' => 'it-works-on-my-machine-t-shirt-white.jpg',
                'attributes' => [
                    'material' => 'cotton',
                    'fit' => 'regular',
                    'origin' => 'portugal',
                    'weight' => 185,
                    'wash_temperature' => 40,
                    'release_date' => '2026-03-02',
                    'print_motif' => 'It works on my machine',
                    'fun_fact' => 'This sentence is older than most web frameworks.',
                ],
                'associations' => ['accessory' => ['MG-4002', 'ST-5003'], 'alternative' => ['TS-1001']],
            ],
            [
                'code' => 'TS-1003',
                'family' => 'clothing',
                'title' => '404 Not Found T-Shirt',
                'claim' => 'You cannot find this shirt. Try again.',
                'description' => '<p>A cotton T-shirt with a big 404 on the front. Good for people who lose things.</p>',
                'image' => '404-not-found-t-shirt-navy.jpg',
                'attributes' => [
                    'material' => 'cotton',
                    'fit' => 'relaxed',
                    'origin' => 'portugal',
                    'weight' => 190,
                    'wash_temperature' => 40,
                    'release_date' => '2026-03-16',
                    'print_motif' => '404',
                    'fun_fact' => '404 is the HTTP status code for Not Found.',
                ],
                'associations' => ['accessory' => ['ST-5001'], 'alternative' => ['TS-1004']],
            ],
            [
                'code' => 'TS-1004',
                'family' => 'clothing',
                'title' => 'Semicolon T-Shirt',
                'claim' => 'One small mark. Many big bugs.',
                'description' => '<p>A relaxed T-shirt with one big semicolon. Simple, and it never forgets the end of the line.</p>',
                'image' => 'semicolon-t-shirt-black.jpg',
                'attributes' => [
                    'material' => 'organic-cotton',
                    'fit' => 'relaxed',
                    'origin' => 'portugal',
                    'weight' => 190,
                    'wash_temperature' => 30,
                    'release_date' => '2026-03-16',
                    'print_motif' => ';',
                    'fun_fact' => 'A missing semicolon can stop a whole program.',
                ],
                'associations' => ['accessory' => ['ST-5002', 'AC-6001'], 'alternative' => ['TS-1003']],
            ],
            [
                'code' => 'TS-1005',
                'family' => 'clothing',
                'title' => 'Sudo T-Shirt',
                'claim' => 'Because I said so.',
                'description' => '<p>A slim T-shirt with one command on the chest. It gets you what you want, as long as you have the rights.</p>',
                'image' => 'sudo-t-shirt-black.jpg',
                'attributes' => [
                    'material' => 'organic-cotton',
                    'fit' => 'slim',
                    'origin' => 'germany',
                    'weight' => 170,
                    'wash_temperature' => 30,
                    'release_date' => '2026-04-13',
                    'print_motif' => 'sudo make me a sandwich',
                    'fun_fact' => 'The command sudo runs another command with the rights of an admin.',
                ],
                'associations' => ['accessory' => ['AC-6002'], 'alternative' => ['TS-1006']],
            ],
            [
                'code' => 'TS-1006',
                'family' => 'clothing',
                'title' => 'Sulu Touch 2026 T-Shirt',
                'claim' => 'Wear the conference.',
                'description' => '<p>The official T-shirt of Sulu Touch 2026. Soft cotton, a clean print and a regular fit.</p>',
                'image' => 'sulu-touch-2026-t-shirt-teal.jpg',
                'attributes' => [
                    'material' => 'cotton',
                    'fit' => 'regular',
                    'origin' => 'portugal',
                    'weight' => 180,
                    'wash_temperature' => 40,
                    'release_date' => '2026-10-08',
                    'print_motif' => 'SULU TOUCH 2026',
                    'fun_fact' => 'This shirt is only for the conference.',
                    'limited_edition' => true,
                ],
                'associations' => ['accessory' => ['AC-6007', 'AC-6008'], 'alternative' => ['TS-1005']],
            ],
            [
                'code' => 'HD-2001',
                'family' => 'clothing',
                'title' => 'Sulu Hoodie',
                'claim' => 'Warm code. Cold office.',
                'description' => '<p>A heavy cotton hoodie with a front pocket. It keeps you warm in every meeting.</p>',
                'image' => 'sulu-hoodie-black.jpg',
                'attributes' => [
                    'material' => 'fleece',
                    'fit' => 'relaxed',
                    'origin' => 'germany',
                    'weight' => 480,
                    'wash_temperature' => 30,
                    'release_date' => '2026-04-13',
                    'print_motif' => 'SULU',
                    'fun_fact' => 'The hoodie is the work uniform of many developers.',
                ],
                'associations' => ['accessory' => ['MG-4001', 'AC-6004'], 'alternative' => ['HD-2002']],
            ],
            [
                'code' => 'HD-2002',
                'family' => 'clothing',
                'title' => 'Merge Conflict Hoodie',
                'claim' => 'Two sides. One hoodie.',
                'description' => '<p>A relaxed hoodie with two colours of text on the chest. It stays calm when your branches do not.</p>',
                'image' => 'merge-conflict-hoodie-navy.jpg',
                'attributes' => [
                    'material' => 'fleece',
                    'fit' => 'relaxed',
                    'origin' => 'germany',
                    'weight' => 490,
                    'wash_temperature' => 30,
                    'release_date' => '2026-05-04',
                    'print_motif' => '<<<<<<< HEAD',
                    'fun_fact' => 'Git marks a merge conflict with these arrow lines.',
                ],
                'associations' => ['accessory' => ['AC-6005'], 'alternative' => ['HD-2003']],
            ],
            [
                'code' => 'HD-2003',
                'family' => 'clothing',
                'title' => 'Ctrl+Z Hoodie',
                'claim' => 'Undo your whole week.',
                'description' => '<p>A regular hoodie with the undo shortcut on the chest. Soft inside, and ready for every bad decision.</p>',
                'image' => 'ctrl-z-hoodie-black.jpg',
                'attributes' => [
                    'material' => 'fleece',
                    'fit' => 'regular',
                    'origin' => 'poland',
                    'weight' => 470,
                    'wash_temperature' => 30,
                    'release_date' => '2026-05-04',
                    'print_motif' => 'Ctrl+Z',
                    'fun_fact' => 'Ctrl+Z undoes your last action in most apps.',
                ],
                'associations' => ['accessory' => ['AC-6006', 'MG-4002'], 'alternative' => ['HD-2001']],
            ],
            [
                'code' => 'HD-2004',
                'family' => 'clothing',
                'title' => 'Rubber Duck Hoodie',
                'claim' => 'Quack. Commit. Repeat.',
                'description' => '<p>A yellow hoodie with a small duck on the chest. It always listens to your problems.</p>',
                'image' => 'rubber-duck-hoodie-yellow.jpg',
                'attributes' => [
                    'material' => 'fleece',
                    'fit' => 'relaxed',
                    'origin' => 'poland',
                    'weight' => 485,
                    'wash_temperature' => 30,
                    'release_date' => '2026-06-01',
                    'print_motif' => 'Duck',
                    'fun_fact' => 'Developers explain bugs to a rubber duck to find them.',
                    'limited_edition' => true,
                ],
                'associations' => ['accessory' => ['AC-6005'], 'alternative' => ['HD-2002']],
            ],
            [
                'code' => 'CP-3001',
                'family' => 'clothing',
                'title' => 'Deploy Friday Cap',
                'claim' => 'Only for brave people.',
                'description' => '<p>A cotton cap with a small patch. One size fits all heads, even before a Friday deploy.</p>',
                'image' => 'deploy-friday-cap-black.jpg',
                'attributes' => [
                    'material' => 'cotton',
                    'fit' => 'regular',
                    'origin' => 'portugal',
                    'weight' => 90,
                    'wash_temperature' => 30,
                    'release_date' => '2026-06-01',
                    'print_motif' => 'DEPLOY FRIDAY',
                    'fun_fact' => 'Many teams never deploy on a Friday.',
                ],
                'associations' => ['accessory' => ['ST-5001'], 'alternative' => ['CP-3002']],
            ],
            [
                'code' => 'CP-3002',
                'family' => 'clothing',
                'title' => 'Semicolon Cap',
                'claim' => 'The end of the line.',
                'description' => '<p>A cotton cap with one small semicolon on the front. Clean, simple and one size.</p>',
                'image' => 'semicolon-cap-mustard.jpg',
                'attributes' => [
                    'material' => 'cotton',
                    'fit' => 'regular',
                    'origin' => 'portugal',
                    'weight' => 90,
                    'wash_temperature' => 30,
                    'release_date' => '2026-06-01',
                    'print_motif' => ';',
                    'fun_fact' => 'In many languages the semicolon ends a statement.',
                ],
                'associations' => ['accessory' => ['ST-5002'], 'alternative' => ['CP-3001']],
            ],
            [
                'code' => 'MG-4001',
                'family' => 'accessories',
                'title' => 'git push Mug',
                'claim' => 'Push your coffee.',
                'description' => '<p>A white or black ceramic mug with a short command on it. It holds 330 ml of coffee.</p>',
                'image' => 'git-push-mug-white.jpg',
                'attributes' => [
                    'material' => 'ceramic',
                    'origin' => 'poland',
                    'weight' => 350,
                    'volume' => 330,
                    'dishwasher_safe' => true,
                    'release_date' => '2026-02-16',
                    'print_motif' => 'git push',
                    'fun_fact' => 'The command git push sends your work to the server.',
                ],
                'associations' => ['accessory' => ['AC-6005'], 'alternative' => ['MG-4002']],
            ],
            [
                'code' => 'MG-4002',
                'family' => 'accessories',
                'title' => 'Coffee Compiler Mug',
                'claim' => 'It turns coffee into code.',
                'description' => '<p>A big ceramic mug with a joke about your job. It holds 450 ml, so you can code longer.</p>',
                'image' => 'coffee-compiler-mug-navy.jpg',
                'attributes' => [
                    'material' => 'ceramic',
                    'origin' => 'poland',
                    'weight' => 420,
                    'volume' => 450,
                    'dishwasher_safe' => true,
                    'release_date' => '2026-02-16',
                    'print_motif' => 'coffee -> code',
                    'fun_fact' => 'A big mug means fewer trips to the kitchen.',
                ],
                'associations' => ['accessory' => ['ST-5004'], 'alternative' => ['MG-4001']],
            ],
            [
                'code' => 'MG-4003',
                'family' => 'accessories',
                'title' => 'Rubber Duck Mug',
                'claim' => 'A good listener, with a handle.',
                'description' => '<p>A yellow ceramic mug in the shape of a duck. Good for coffee and for talking about bugs.</p>',
                'image' => 'rubber-duck-mug.jpg',
                'attributes' => [
                    'material' => 'ceramic',
                    'origin' => 'poland',
                    'weight' => 380,
                    'volume' => 350,
                    'dishwasher_safe' => false,
                    'release_date' => '2026-06-01',
                    'fun_fact' => 'The rubber duck method is real, and it works.',
                    'limited_edition' => true,
                ],
                'associations' => ['accessory' => ['AC-6005'], 'alternative' => ['MG-4001']],
            ],
            [
                'code' => 'ST-5001',
                'family' => 'accessories',
                'title' => '404 Sticker',
                'claim' => 'Not found, but stuck.',
                'description' => '<p>A vinyl sticker with a big 404. It sticks on laptops, bottles and walls.</p>',
                'image' => '404-sticker.jpg',
                'attributes' => [
                    'material' => 'vinyl',
                    'origin' => 'germany',
                    'weight' => 5,
                    'release_date' => '2026-02-16',
                    'print_motif' => '404',
                    'fun_fact' => 'You can put stickers on a laptop. Many people do.',
                ],
                'associations' => ['accessory' => ['ST-5004'], 'alternative' => ['ST-5002']],
            ],
            [
                'code' => 'ST-5002',
                'family' => 'accessories',
                'title' => 'Semicolon Sticker',
                'claim' => 'Small, and not forgotten.',
                'description' => '<p>A round vinyl sticker with a semicolon. It is water-proof and easy to peel off.</p>',
                'image' => 'semicolon-sticker.jpg',
                'attributes' => [
                    'material' => 'vinyl',
                    'origin' => 'germany',
                    'weight' => 5,
                    'release_date' => '2026-02-16',
                    'print_motif' => ';',
                    'fun_fact' => 'A semicolon is a very small sticker.',
                ],
                'associations' => ['accessory' => ['ST-5004'], 'alternative' => ['ST-5001']],
            ],
            [
                'code' => 'ST-5003',
                'family' => 'accessories',
                'title' => 'Sulu Logo Sticker',
                'claim' => 'The Sulu logo, now sticky.',
                'description' => '<p>A die-cut vinyl sticker with a simple geometric cube logo in dark blue. It is water-proof.</p>',
                'image' => 'sulu-logo-sticker.jpg',
                'attributes' => [
                    'material' => 'vinyl',
                    'origin' => 'germany',
                    'weight' => 5,
                    'release_date' => '2026-10-08',
                    'print_motif' => 'Sulu',
                    'fun_fact' => 'Stickers are the cheapest way to show your favourite tool.',
                ],
                'associations' => ['alternative' => ['ST-5004']],
            ],
            [
                'code' => 'ST-5004',
                'family' => 'accessories',
                'title' => 'Sticker Pack (5 pieces)',
                'claim' => 'Five stickers. Zero excuses.',
                'description' => '<p>Five different vinyl stickers in one pack. A good gift for every laptop.</p>',
                'image' => 'sticker-pack-5-pieces.jpg',
                'attributes' => [
                    'material' => 'vinyl',
                    'origin' => 'germany',
                    'weight' => 25,
                    'release_date' => '2026-02-16',
                    'fun_fact' => 'A full laptop lid has about ten stickers.',
                ],
                'associations' => ['alternative' => ['ST-5001']],
            ],
            [
                'code' => 'AC-6001',
                'family' => 'accessories',
                'title' => 'Tote Bag',
                'claim' => 'Carries your laptop and your lunch.',
                'description' => '<p>A strong canvas bag with a long handle. It has space for a laptop and a lunch box.</p>',
                'image' => 'tote-bag.jpg',
                'attributes' => [
                    'material' => 'canvas',
                    'origin' => 'portugal',
                    'weight' => 200,
                    'release_date' => '2026-03-02',
                    'print_motif' => 'npm install coffee',
                    'fun_fact' => 'A tote bag holds more than a pocket.',
                ],
                'associations' => ['accessory' => ['AC-6002'], 'alternative' => ['AC-6003']],
            ],
            [
                'code' => 'AC-6002',
                'family' => 'accessories',
                'title' => 'Dotted Notebook',
                'claim' => 'For ideas that never ship.',
                'description' => '<p>An A5 notebook with dotted pages and a hard cover. It has 160 pages for your sketches.</p>',
                'image' => 'dotted-notebook.jpg',
                'attributes' => [
                    'material' => 'paper',
                    'origin' => 'austria',
                    'weight' => 180,
                    'release_date' => '2026-03-02',
                    'fun_fact' => 'Many developers still draw on paper first.',
                ],
                'associations' => ['accessory' => ['AC-6007'], 'alternative' => ['AC-6001']],
            ],
            [
                'code' => 'AC-6003',
                'family' => 'accessories',
                'title' => 'Laptop Sleeve',
                'claim' => 'A coat for your laptop.',
                'description' => '<p>A soft grey sleeve for a 14 inch laptop. It protects against scratches and small drops.</p>',
                'image' => 'laptop-sleeve.jpg',
                'attributes' => [
                    'material' => 'polyester',
                    'origin' => 'poland',
                    'weight' => 150,
                    'release_date' => '2026-03-02',
                    'fun_fact' => 'A good sleeve saves a good laptop.',
                ],
                'associations' => ['accessory' => ['ST-5001'], 'alternative' => ['AC-6001']],
            ],
            [
                'code' => 'AC-6004',
                'family' => 'accessories',
                'title' => 'Water Bottle',
                'claim' => 'Water is a drink too.',
                'description' => '<p>A steel bottle with a screw cap. It keeps drinks cold for a day and hot for six hours.</p>',
                'image' => 'water-bottle.jpg',
                'attributes' => [
                    'material' => 'steel',
                    'origin' => 'germany',
                    'weight' => 280,
                    'volume' => 500,
                    'dishwasher_safe' => false,
                    'release_date' => '2026-04-13',
                    'fun_fact' => 'Drinking water helps you think.',
                ],
                'associations' => ['accessory' => ['ST-5001'], 'alternative' => ['MG-4001']],
            ],
            [
                'code' => 'AC-6005',
                'family' => 'accessories',
                'title' => 'Debug Duck',
                'claim' => 'Explain your bug. It listens.',
                'description' => '<p>A small yellow rubber duck with tiny round glasses. It never talks back and it floats.</p>',
                'image' => 'debug-duck.jpg',
                'attributes' => [
                    'material' => 'rubber',
                    'origin' => 'germany',
                    'weight' => 60,
                    'release_date' => '2026-06-01',
                    'fun_fact' => 'Saying a problem out loud often solves it.',
                ],
                'associations' => ['accessory' => ['ST-5004'], 'alternative' => ['MG-4003']],
            ],
            [
                'code' => 'AC-6006',
                'family' => 'accessories',
                'title' => 'Desk Mat',
                'claim' => 'Keeps your coffee off the wood.',
                'description' => '<p>A large desk mat with a fine grid. It is soft, it does not slip and it fits keyboard and mouse.</p>',
                'image' => 'desk-mat.jpg',
                'attributes' => [
                    'material' => 'polyester',
                    'origin' => 'poland',
                    'weight' => 450,
                    'release_date' => '2026-04-13',
                    'fun_fact' => 'A big mat gives your mouse room to move.',
                ],
                'associations' => ['accessory' => ['MG-4001'], 'alternative' => ['AC-6003']],
            ],
            [
                'code' => 'AC-6007',
                'family' => 'accessories',
                'title' => 'Lanyard',
                'claim' => 'For people who lose badges.',
                'description' => '<p>A soft teal lanyard with a metal clip. The word SULU is printed along the whole band.</p>',
                'image' => 'lanyard.jpg',
                'attributes' => [
                    'material' => 'polyester',
                    'origin' => 'germany',
                    'weight' => 30,
                    'release_date' => '2026-10-08',
                    'print_motif' => 'SULU',
                    'fun_fact' => 'A good lanyard survives a whole conference.',
                ],
                'associations' => ['accessory' => ['AC-6008'], 'alternative' => ['AC-6002']],
            ],
            [
                'code' => 'AC-6008',
                'family' => 'accessories',
                'title' => 'Enamel Pin',
                'claim' => 'Small, shiny, a bit proud.',
                'description' => '<p>A small hard enamel pin in the shape of a semicolon. It comes on a backing card.</p>',
                'image' => 'enamel-pin.jpg',
                'attributes' => [
                    'material' => 'steel',
                    'origin' => 'germany',
                    'weight' => 8,
                    'release_date' => '2026-06-01',
                    'print_motif' => ';',
                    'fun_fact' => 'Pins are small, but people notice them.',
                    'limited_edition' => true,
                ],
                'associations' => ['alternative' => ['ST-5002']],
            ],
        ];
    }
}
